api/urls.py
from django.conf.urls import url

from .views import (APIUserList,
                    APIUserDetail,
                    APIVoteFor,)


urlpatterns = [
    url(r'^list$', APIUserList.as_view()),
    url(r'^customer/(?P<pk>[0-9]+)$', APIUserDetail.as_view()),
    url(r'^vote/(?P<pk>[0-9]+)$', APIVoteFor.as_view())
]

customers/urls.py
from django.conf.urls import url

from .views import (add_customer_view,
                    customer_detail_view,
                    delete_view,
                    export_customers_view,
                    list_view,
                    vote_for,
                    voting_view)


urlpatterns = [
    url(r'^$', list_view, name='list'),
    url(r'^add_customer/$', add_customer_view, name='new_customer'),
    url(r'^(?P<pk>[0-9]+)/$', customer_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', delete_view, name='delete'),
    url(r'^export/$', export_customers_view, name='export_customers'),
    url(r'^voting/$', voting_view, name='voting'),
    url(r'^voting/(?P<pk>[0-9]+)$', vote_for, name='vote_for'),
]

django_test_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # Админка
    url(r'^admin/', include(admin.site.urls)),
    # клиенты
    url(r'', include('customers.urls', namespace='customers')),
    # API
    url(r'^api/', include('api.urls', namespace='api')),
]

customers/models.py
from datetime import date

from django.db import models
from django.core.validators import MaxValueValidator


class Customer(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    birthday = models.DateField()
    photo_link = models.URLField(max_length=100)
    votes = models.IntegerField(default=0, validators=[MaxValueValidator(10)])

    @property
    def age(self):
        print(dir(self.birthday))
        days = date.today().year - self.birthday.year
        return days

    def add_vote(self):
        self.votes += 1
        self.save()

customers/forms.py
from django import forms

from .models import Customer


class NewCustomerForm(forms.ModelForm):
    birthday = forms.DateField(widget=forms.TextInput(
        attrs={'placeholder': 'YYYY-MM-DD', }
    ))

    class Meta:
        model = Customer
        fields = ('name',
                  'surname',
                  'birthday',
                  'photo_link',)

api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import CustomerSerializer
from customers.models import Customer


class APIUserList(APIView):
    """API для работы со списком пользователей."""

    def get(self, request):
        """Доступ к списку пользоватей."""
        customers = Customer.objects.all()
        serializer = CustomerSerializer(customers, many=True)
        return Response(serializer.data)

    def post(self, request):
        """Создание пользователя."""
        serializer = CustomerSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class APIUserDetail(APIView):
    """Some text."""

    def get(self, request, pk):
        """Данные конкретного пользователя."""
        customer = get_object_or_404(Customer, pk=pk)
        serializer = CustomerSerializer(customer)
        return Response(serializer.data)

    def delete(self, request, pk):
        """Удаление пользователя."""
        customer = get_object_or_404(Customer, pk=pk)
        customer.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class APIVoteFor(APIView):
    def put(self, request, pk):
        """Голосование за определенного пользователя."""
        customer = get_object_or_404(Customer, pk=pk)
        flag = customer.add_vote()
        serializer = CustomerSerializer(customer)
        if flag:
            return Response(serializer.data)
        else:
            Response(serializer.errors, status=status.HTTP_423_LOCKED)

customers/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt

from .forms import NewCustomerForm
from .models import Customer
from .utils import create_report


def list_view(request):
    queryset = Customer.objects.all()
    query_name = request.GET.get('q')
    if query_name:
        queryset = queryset.filter(
            Q(name__icontains=query_name) |
            Q(surname__icontains=query_name)
        ).distinct()
    query_order = request.GET.get('ordering')
    if query_order:
        queryset = queryset.order_by(query_order)
    context = {
        'customers': queryset
    }
    return render(request, 'customers/customers_list.html', context=context)


def add_customer_view(request):
    form = NewCustomerForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('customers:list')
    context = {
        'form': form,
    }
    return render(request, 'customers/customers_new.html', context=context)


def customer_detail_view(request, pk):
    instance = get_object_or_404(Customer, pk=pk)
    context = {
        'customer': instance,
    }
    return render(request, 'customers/customers_detail.html', context=context)


def delete_view(request, pk):
    get_object_or_404(Customer, pk=pk).delete()
    return redirect('customers:list')


def voting_view(request):
    queryset = Customer.objects.all()
    context = {
        'cards': queryset
    }
    return render(request, 'customers/voting.html', context=context)


def vote_for(request, pk):
    get_object_or_404(Customer, pk=pk).add_vote()
    return redirect('customers:voting')


@csrf_exempt
def export_customers_view(request):
    response = create_report()
    return response

templates/customers/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Тестовое задание</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>

<div class="container">
  <h2><a href="/">Главная</a></h2>
  {% block content %}
  {% endblock %}
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>

templates/customers/customers_detail.html
{% extends "customers/base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <img src="{{ customer.photo_link }}" alt="">
  </div>
  <div class="col-md-6">
    <p><b>Имя</b>: {{ customer.name }}</p>
    <p><b>Фамилия</b>: {{ customer.surname }}</p>
    <p><b>Дата рождения</b>: {{ customer.birthday }} ( {{ customer.age }} лет) </p>
  </div>
</div>

{% endblock content %}

templates/customers/customers_list.html
{% extends "customers/base.html" %}

{% block content %}
<h2>Список всех клиентов</h2>


<form class="form-inline" role="form">
  <label>Фильтр по имени/фамилии</label>
  <div class="form-group">
    <label class="sr-only">Email</label>
    <input name="q" class="form-control" placeholder="Введи фрагмент имя/фамилия" value="{{ request.GET.q }}">
  </div>
  <label for="form-control">Сортировать по</label>
  <select class="form-control" name="ordering" value="{{ request.GET.ordering }}">
    <option value="name">Имя</option>
    <option value="surname">Фамилия</option>
    <option value="birthday">Дата рождения</option>
  </select>
  <button type="submit" class="btn btn-default">Ввод</button>
</form>
<br>
<table class="table table-striped">
  <tr>
    <th>Имя</th>
    <th>Фамилия</th>
    <th>Дата рождения</th>
    <th>Просмотр карточки</th>
    <th>Удаление</th>
  </tr>
  {% for customer in customers %}
  <tr>
    <td>{{ customer.name }}</td>
    <td>{{ customer.surname }}</td>
    <td>{{ customer.birthday }}</td>
    <td>
      <a href="{% url 'customers:detail' customer.id %}"><span class="glyphicon glyphicon-eye-open"></span></a>
    </td>
    <td>
      <a href="{% url 'customers:delete' customer.id %}"><span class="glyphicon glyphicon-remove"></span></a>
    </td>
  </tr>

  {% empty %}
  <h3>Пока нет пользователей</h3>
  {% endfor %}
</table>
<hr>
<a href="{% url 'customers:voting' %}">Голосование</a>
<hr>
<a href="{% url 'customers:new_customer' %}">Добавить нового клиента</a>
<hr>
<a href="{% url 'customers:export_customers' %}">Сохранить список клиента</a>
{% endblock content %}

templates/customers/customers_new.html
{% extends "customers/base.html" %}

{% block content %}

<div id="comment_form">
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить пользователя" name="" id="">
  </form>
</div>

{% endblock content %}

templates/customers/voting.html
{% extends "customers/base.html" %}

{% block content %}
<h2>Голосование</h2>
{% if error_message %}
  Голосование за выбранного участника прекращено
{% endif %}
<div class="row">
{% for card in cards %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="{{ card.photo_link }}">
      <div class="caption">
        <p>
          <a href="{% url 'customers:vote_for' card.id %}" class="btn btn-primary
          {% if card.votes >= 10 %}
          disabled
          {% endif %}
          " role="button">Голосовать</a>
        </p>
        <p>{{ card.votes }} голосов</p>
      </div>
    </div>
  </div>
{% empty %}
<h3>Пока нет пользователей</h3>
{% endfor %}
</div>

{% endblock content %}